services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: my_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"  # Adjust based on your app
    volumes:
      - .:/app

volumes:
  postgres_data:
